version: '3.7'
services:
   main:
      build:
         context: ./main_microservice
         dockerfile: Dockerfile
      ports:
         - 8000:8000
      volumes:
         - ./main_microservice:/app
      container_name: main
      depends_on:
         - database
   database:
      image: postgres:13
      volumes:
         - postgres_data:/var/lib/postgresql/data/
      environment:
         - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
   postgres_data:
