# Generated by Django 4.1.4 on 2022-12-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_task_created_at_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(max_length=20),
        ),
    ]
